GET http://localhost:3000/RijksStrike

###

GET http://localhost:3000/RijksStrike/rembrandt

###

GET http://localhost:3000/RijksStrike/5dd6d78b6a4fb304439280c5

###

POST http://localhost:3000/RijksStrike
Content-Type: application/json

{
  "RijksID": "nl-SK-C-216",
  "fvComment": "John & Ben"
}

###

DELETE http://localhost:3000/RijksStrike/5dd6d78b6a4fb304439280c5

###

PATCH http://localhost:3000/RijksStrike/5de609e126ed9078de4ef799/John & Ben
